version: '3.8'

services:
  scrapy:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - PYTHONPATH=/app
    container_name: scrapy_container
    depends_on:
      - postgres
      - redis
      - mongo
    volumes:
      - .:/app
    networks:
      - my_network
    # command: scrapy crawl job_spider
    command: ["tail", "-f", "/dev/null"]

  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - my_network

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - my_network

  mongo:
    image: mongo:6
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: Passw0rd
      MONGO_INITDB_DATABASE: canaria
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
